### ISSUE TITLE
OpenBuilds_mm.pp

### ISSUE THREAD

**Issue by bobdivx** [OpenBuilds/OpenBuilds-Vectric-Postprocessor#1]
hi there is no way to add this in ASPIRE software

thank you

**Comment by petervanderwalt** [comment]
See https://docs.openbuilds.com/doku.php?id=docs:software:vectric

**Comment by bobdivx** [comment]
hello

there is an error with your .pp file so I tried to redo it.


+================================================
+
+ Grbl - Vectric machine output configuration file
+
+================================================
+
+ History
+
+ Who      When       What
+ ======== ========== ===========================
+ EdwardP  28/11/2014 Written from GCode_mm.pp
+                     Added arc move support
+ EdwardP  11/02/2015 Commented out arcs as these
+                     slow GRBL performance appear
+                     interpolated anyway
+ EdwardP  18/06/2015 Explicitly set absolute mode (G90)
+ Mark     24/11/2015 Updated for interim 0.9 spec.
+                     Renaming to be machine specific.
+                     Removing M30 from Footer.
+ EdwardP  01/02/2018 Updated according to 1.1 spec
+                     Changed to 1.3 precision
+                     Spindle off (M5) in footer
+                     Added VTransfer Direct Output
+ EdwardP  07/12/2018 Added grbl laser 1.1 support.
+                     - Power variable (0-1000 range)
+                     - Power on change only
+                     - [P] added to feedrate records
+                     - New laser record types:
+                       o JET_TOOL_ON
+                       o JET_TOOL_OFF
+                       o JET_TOOL_POWER
+ MohamedM 13/12/2018 Move M3 and [S] from the header
+                     to a new SPINDLE_ON section which
+                     is not output in laser toolpaths
+                     or when the spindle speed is invalid (negative).
+ EdwardP 20/12/2018  Re-enabled arcs in response to
+                     customer feedback ZD105327
+ CharlotteP 26/03/2020 Updated to open builds from base
+                     grbl with ZD141201
+ PetervdWalt 11/6/2020 Updated Header to include G20/G90 Modals
+                     for OpenBuilds BlackBox
+ Bobdivx 20/01/22    there is an error with your .pp file so I tried to redo it**
+ ======== ========== ===========================

POST_NAME = "OpenBuilds GRBL (mm) (*.GCODE)"

POST_BASE = "Grbl_mm.pp"

FILE_EXTENSION = "GCODE"


+================================================
+
+    Block definitions for toolpath output
+
+================================================

+---------------------------------------------------
+  Commands output at the start of the file
+---------------------------------------------------

begin HEADER

"G21"
"M3 S10000"
"G90"
"G1[ZH]F228.6"
"G0[XH][YH]"


begin RAPID_MOVE

"G0[X][Y][Z]"


begin FIRST_FEED_MOVE

"G1[X][Y][Z][F]"

begin FOOTER

"G1[ZH]"
"G0[XH][YH]"
"M5"




my problem is: G21
M3 S10000
G90
G1Z20.000F28.6

when it should be:
G21
M3 S10000
G90
G1Z0.000F28.6

thanks

**Comment by petervanderwalt** [comment]
No issues with the post, widely used and even included in V10.5+ versions of Vectric. 

Post a screenshot of your Help > About page from within vectric?
